name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    #Don't deploy unless on the main branch
    if: github.ref == 'refs/heads/main'    
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ secrets.DOCKERHUB_USERNAME }}/devops-labs:latest
          containerAppName: devops-app
          containerAppEnvironment: devops-app-env
          resourceGroup: devsecops-lab
          location: australiaeast
          targetPort: 5000

#There were modifications in this step that were made due to jq being removed in aws-cli - https://github.com/Azure/azure-cli/issues/29830
  submit_results:
    needs: [deploy]
    #Don't submit results unless on the main branch
    if: github.ref == 'refs/heads/main'    
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get Azure Access Token
        id: token-gen
        run: |
          ACCESS_TOKEN=$(az account get-access-token | jq -r .accessToken)
          echo "azureAccessToken=$ACCESS_TOKEN" >> $GITHUB_ENV

      # - name: Upload reports
      #   env:
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #     AZURE_ACCESS_TOKEN: ${{ env.azureAccessToken }}
      #   run: |
      #     WEEK3_CONTAINER=$(curl -X POST -H "Authorization: Bearer $AZURE_ACCESS_TOKEN" -d "$DOCKERHUB_USERNAME/devops-labs" https://devsecops-ver.azurewebsites.net/api/week3-container)
      #     echo "Week3 container upload: $WEEK3_CONTAINER"
