name: Python test and build

on: [push]

jobs:
  build:
    needs: sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-labs:latest

  sonarqube:
    needs: test
    if: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_URL }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest api_tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: test-results
          path: junit/test-results.xml

#There were modifications in this step that were made due to jq being removed in aws-cli - https://github.com/Azure/azure-cli/issues/29830
#not publishing yet
  # submit_results:
  #   needs: [build]
  #   if: true
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install jq
  #       run: sudo apt-get install -y jq

  #     - name: Get Azure Access Token
  #       id: token-gen
  #       # execute qj commands and az commmands in the same runner environment to get around issue https://github.com/Azure/azure-cli/issues/29830. Can be fixed up after the release to bring back jq.
  #       run: |
  #         ACCESS_TOKEN=$(az account get-access-token | jq -r .accessToken)
  #         echo "azureAccessToken=$ACCESS_TOKEN" >> $GITHUB_ENV

  #     - name: Upload reports
  #       env:
  #         DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #         AZURE_ACCESS_TOKEN: ${{ env.azureAccessToken }}
  #       run: |
  #         WEEK2_SUBMIT=$(curl -X POST -H "Authorization: Bearer $AZURE_ACCESS_TOKEN" -d "https://$FQDN" https://devsecops-ver.azurewebsites.net/api/week2-submit)
  #         echo "Week2 submit: $WEEK2_SUBMIT"
